name: rabbitmq-apm-simple

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.18
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.18
    container_name: apm-server
    command: >
      apm-server -e
        -E apm-server.host=0.0.0.0:8200
        -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
        -E apm-server.fleet.enabled=false
        -E apm-server.data_streams.enabled=false
        -E setup.template.enabled=true
        -E setup.template.overwrite=true
        -E setup.ilm.enabled=false
        -E apm-server.register.ingest.pipeline.enabled=true
        -E setup.kibana.host=http://kibana:5601
    ports:
      - "8200:8200"
    depends_on:
      - elasticsearch

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  es_data:
  rabbitmq_data: